---

# Secret Values in group_vars/zuul/zuul_vault.yaml

zuul_log_server_tag: "alpine"
#zuul_mariadb_tag: "11.1"
#zuul_zuul_tag: "9.2.0"
#zuul_nodepool_tag: "9.0.0"
#zuul_zookeeper_tag: "3.7.2"
zuul_mariadb_tag: "11.4.2"
zuul_nodepool_tag: "10.0.0"
zuul_zookeeper_tag: "3.9.2"
zuul_zuul_tag: "10.1.0"

zuul_statsd_host: "213.131.230.154"

zuul_webserver_fqdn: "{{ prod_zuul_webserver_fqdn if ('zuul-logs-dev.scs.community' not in inventory_hostname) else dev_zuul_webserver_fqdn }}"
zuul_logserver_fqdn: "{{ prod_zuul_logserver_fqdn if ('zuul-logs-dev.scs.community' not in inventory_hostname) else dev_zuul_logserver_fqdn }}"
dev_zuul_webserver_fqdn: "zuul-dev.scs.community"
dev_zuul_logserver_fqdn: "zuul-logs-dev.scs.community"
prod_zuul_webserver_fqdn: "zuul.scs.community"
prod_zuul_logserver_fqdn: "zuul-logs.scs.community"
zuul_webserver_admin_mail: "oliver.kautz@gonicus.de"
zuul_cn_name: "{{ zuul_cn if ('zuul-logs-dev.scs.community' not in inventory_hostname) else zuul_dev_cn }}"
zuul_cn: "zuul"
zuul_dev_cn: "zuul_dev"

add_ssh_keys_from_github:
- o-otte
- master-caster
- joshmue
- scoopex
- fkr
- pixelphantomx
- matofeder
