---
# copy cloud connection information
- name: Populate and copy clouds.yaml to VM
  template:
    src: "templates/clouds.yaml.j2"
    dest: "/etc/openstack/clouds.yaml"
    owner: root
    group: zuul
    mode: 0640
  become: true
  vars:
    zuul_clouds: "{{ vault_zuul_clouds_yaml if ('zuul-logs-dev.scs.community' not in inventory_hostname) else vault_zuul_dev_clouds_yaml }}"
  tags: clouds-yaml

- name: Copy pem files (e.g. for github)
  ansible.builtin.template:
    src: "templates/scs-zuul-app-private-key.pem.j2"
    dest: "/opt/zuul/zuul_configuration/pem-files/scs-zuul-app-private-key.pem"
    owner: root
    group: root
    mode: 0644

# install recommended elements for zuul purposes
- name: Deploy additionals elements used for DIB
  ansible.builtin.copy:
    src: elements/
    dest: /srv/nodepool/elements/
    owner: root
    group: "{{ zuul_group }}"
    mode: 0644
  become: true

- name: Copy zuul logging configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zuul_component_conf_dirs.zuul }}/{{ item }}"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_group }}"
    mode: 0644
  loop:
    - logging.conf
    - executor-logging.conf
    - web-logging.conf

- name: Copy nodepool builder logging config
  ansible.builtin.copy:
    src: builder-logging.conf
    dest: "{{ zuul_component_conf_dirs.nodepool_builder }}/logging.conf"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_group }}"
    mode: 0644

- name: Copy nodepool launcher logging config
  ansible.builtin.copy:
    src: launcher-logging.conf
    dest: "{{ zuul_component_conf_dirs.nodepool_launcher }}/logging.conf"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_group }}"
    mode: 0644

- name: Copy zookeeper certificate generator script
  ansible.builtin.copy:
    src: "{{ item['file'] }}"
    dest: "{{ zuul_component_conf_dirs.certs }}/{{ item['file'] }}"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_group }}"
    mode: "{{ item['mode'] }}"
  loop:
    - file: zk-ca.sh
      mode: "0755"
    - file: openssl.cnf
      mode: "0644"

- name: Copy log server mime types
  ansible.builtin.copy:
    src: mime.types
    dest: "{{ zuul_component_conf_dirs.log_server }}/mime.types"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_group }}"
    mode: 0644

- name: Copy log server certificate
  ansible.builtin.copy:
    src: server.crt
    dest: "{{ zuul_component_conf_dirs.log_server }}/server.crt"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_group }}"
    mode: 0600
