---
# handlers file for zuul

- name: Smart reload scheduler
  community.docker.docker_container_exec:
    container: zuul_scheduler
    command: /usr/bin/bash -C "/usr/local/bin/zuul-scheduler smart-reconfigure"


