---
- name: Check if node_exporter is installed
  ansible.builtin.stat:
    path: /usr/local/bin/node_exporter
    checksum_algorithm: sha256
    get_md5: no
  check_mode: no
  changed_when: false
  failed_when: false
  register: node_exporter_binary

- name: Install node_exporter from github release
  ansible.builtin.unarchive:
    dest: /usr/local/bin
    extra_opts:
      - "--strip-components=1"
      - "--wildcards"
      - "*/node_exporter"
    group: root
    owner: root
    mode: "u=rwx,g=rx,o=rx"
    remote_src: yes
    src: "{{ node_exporter_dist }}"
  when: node_exporter_binary.stat.checksum is not defined or node_exporter_binary.stat.checksum != node_exporter_sha256

- name: Ensure prometheus-node-exporter systemd service exists
  ansible.builtin.copy:
    src: prometheus-node-exporter.service
    dest: /etc/systemd/system/prometheus-node-exporter.service
  register: node_exporter_systemd
  notify: restart prometheus-node-exporter

- name: Reload systemd
  ansible.builtin.command: /bin/systemctl daemon-reload
  when: node_exporter_systemd.changed

- name: Ensure prometheus-node-exporter is enabled and started
  ansible.builtin.service:
    name: prometheus-node-exporter
    enabled: yes
    state: started
    use: service
