---
- name: Check if statsd_exporter is installed
  ansible.builtin.stat:
    path: /usr/local/bin/statsd_exporter
    checksum_algorithm: sha256
  check_mode: true
  changed_when: false
  failed_when: false
  register: statsd_exporter_binary

- name: Install statsd_exporter from github release
  ansible.builtin.unarchive:
    dest: /usr/local/bin
    extra_opts:
      - "--strip-components=1"
      - "--wildcards"
      - "*/statsd_exporter"
    group: root
    owner: root
    mode: "u=rwx,g=rx,o=rx"
    remote_src: true
    src: "{{ statsd_exporter_dist }}"
  when: statsd_exporter_binary.stat.checksum is not defined or statsd_exporter_binary.stat.checksum != statsd_exporter_sha256

- name: Ensure prometheus-statsd-exporter systemd service exists
  ansible.builtin.copy:
    src: prometheus-statsd-exporter.service
    dest: /etc/systemd/system/prometheus-statsd-exporter.service
  register: statsd_exporter_systemd
  notify: Restart prometheus-statsd-exporter

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: statsd_exporter_systemd.changed

- name: Ensure prometheus-statsd-exporter is enabled and started
  ansible.builtin.service: 
    name: prometheus-statsd-exporter
    enabled: true
    state: started
    use: service
