---
node_exporter_filename: node_exporter-1.7.0.linux-amd64.tar.gz
node_exporter_dist: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
node_exporter_sha256: a550cd5c05f760b7934a2d0afad66d2e92e681482f5f57a917465b1fba3b02a6
