---

- name: generate SSH key for nodepool
  hosts: localhost
  tasks:
    - community.crypto.openssh_keypair:
        path: "{{ playbook_dir }}/nodepool"
        type: rsa
        size: 4096
        state: present


- name: setup zuul playbook
  hosts: zuul
  roles:
     - name: setup zuul role
       role: osism.services.zuul
       become: true
       vars:
         zuul_user: "root"

