---

- name: generate SSH key for nodepool
  hosts: localhost
  tasks:
    - community.crypto.openssh_keypair:
        path: "{{ playbook_dir }}/nodepool"
        type: rsa
        size: 4096
        state: present

# - name: Pull caddy docker container
#   hosts: zuul
#   become: true
#   pre_tasks:
#     - name: Creates directory
#       file:
#         path: /opt/caddy
#         state: directory
#     - name: Copy file with owner and permissions
#       ansible.builtin.copy:
#         src: Caddyfile
#         dest: /opt/caddy/Caddyfile
#         owner: root
#         group: root
#         mode: '0644'
#   tasks:
#     - docker_image:
#         name: "caddy"
#         source: pull
#         state: present
#     - docker_container:
#         name: caddy
#         image: caddy
#         state: started
#         networks:
#           - name: "zuul_default"
#         ports:
#           - "0.0.0.0:80:80/tcp"
#           - "0.0.0.0:443:443/tcp"
#         volumes:
#           - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
      
- name: setup zuul playbook
  hosts: zuul
  vars_files:
        - ./zuul-config.yaml
  pre_tasks:
    - name: install docker python libraries
      become: true
      ansible.builtin.pip:
        name: docker

    - name: install docker-compose python libraries
      become: true
      ansible.builtin.pip:
        name: docker-compose
  roles:
     - name: setup zuul role
       role: osism.services.zuul
       become: true

